---
- name: Configure spamass-milter
  lineinfile:
    dest: "/etc/default/spamass-milter"
    regexp: "^OPTIONS=.+-u spamass-milter"
    # -i 127.0.0.1: ignore localhost
    # -m: don't change subject header
    # -r 15: reject high scoring spam messages (score of 5+ get's marked as spam)
    # -I: ignore mail by logged in users
    line: 'OPTIONS="-u spamass-milter -i 127.0.0.1 -m -r 15 -I"'
    state: present
  notify: restart spamass-milter

- name: Remove redudant user spamd
  user:
    name: spamd
    state: absent

- name: Configure spamd via /etc/default/spamassassin
  lineinfile:
    dest: "/etc/default/spamassassin"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: "^CRON="  # Update spam rules nightly
      line: "CRON=1"

    - regexp: "^OPTIONS="  # run spamd with non-root debian-spamd user
      line: 'OPTIONS="--create-prefs --max-children 5 --helper-home-dir=/var/lib/spamassassin -u debian-spamd -g debian-spamd -x"'
      
  notify: restart spamassassin daemon
