---
- hosts: myplatform
  remote_user: root

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Safe upgrade of all packages
      apt:
        update_cache: yes
        cache_valid_time: 21600 # 6hrs
        upgrade: safe  # does not remove any packages

  tasks:
    # todo: separate out tasks per section

    # host name section 
    - name: Rename hostname in /etc/hostname
      hostname:
        name: "{{ server_hostname }}"
      notify: restart networking

    - name: Rename ipv4 hostname in /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: "^{{ ipv4_address }}"
        line: "{{ ipv4_address }} {{ server_hostname }}"
        state: present
      notify: restart networking

    - name: Rename ipv6 hostname in /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: "^{{ ipv6_address }}"
        line: "{{ ipv6_address }} {{ server_hostname }}"
        state: present
      when: (ipv6_address is defined) and (ipv6_address|length > 0)
      notify: restart networking

    # automated security upgrades section
    - name: Check that we have required packages for auto-upgrades
      apt:
        state: present
        name:
          - unattended-upgrades
          - apt-listchanges

    - name: Configure auto-upgrades for security
      template:
        src: "templates/{{ item }}.j2"
        dest: "/etc/apt/apt.conf.d/{{ item }}"
        owner: root
        mode: u=rw,g=r,o=r
        backup: yes
      loop:
        - 50unattended-upgrades
        - 20auto-upgrades

  handlers:
    - name: restart networking
      service:
        name: networking
        state: restarted
