---
- hosts: myplatform
  remote_user: root

  vars_files:
    - vars.yml

  pre_tasks:

    - include_tasks: hostname.yml

    - name: Remove dependencies that are no longer required from a
        previous update
      apt:
        autoremove: yes

    - name: Do a dist-upgrade. Unused packages may be removed and new
        ones added
      apt:
        update_cache: yes
        cache_valid_time: 3600 # 1 hr
        upgrade: dist

  tasks:

    - include_tasks: ssh.yml
    - include_tasks: unattended_upgrades.yml
    - include_tasks: reboot_required_check.yml

  handlers:
    - name: restart networking
      service:
        name: networking
        state: restarted

    - name: restart ssh
      service: name=ssh state=restarted
