---
- hosts: myplatform
  remote_user: root

  vars_files:
    - vars.yml

  vars:
    - private_vars_location: "/root/private_vars"

  pre_tasks:

    - block:
      - name: Check that we have our private variables file in correct location
        stat: path="{{ private_vars_location }}/vars.yml"
        register: private_vars_file

      - name: Include private vars
        include_vars: "{{ private_vars_location }}/vars.yml"
        when: private_vars_file.stat.exists

      - name: Create private vars template
        include_tasks: private_vars_template.yml
        when: not private_vars_file.stat.exists

      delegate_to: 127.0.0.1

    - include_tasks: hostname.yml

    - name: Remove dependencies that are no longer required from a
        previous update
      apt:
        autoremove: yes

    - name: Do a dist-upgrade. Unused packages may be removed and new
        ones added
      apt:
        update_cache: yes
        cache_valid_time: 3600 # 1 hr
        upgrade: dist

  tasks:

    - include_tasks: timezone.yml
    - include_tasks: ssh.yml
    - include_tasks: unattended_upgrades.yml
    - include_tasks: ssl_cert.yml
    - include_tasks: web_server_setup.yml
      tags:
        - web_server
    - include_tasks: mail_server_setup.yml
      tags:
        - mail_server

    - name: Ensure rsync is installed
      apt: pkg=rsync state=present

    - include_tasks: reboot_required_check.yml

  handlers:
    - name: restart networking
      service:
        name: networking
        state: restarted

    - name: restart ssh
      service: name=ssh state=restarted

    - name: restart nginx
      service: name=nginx state=restarted

    - name: reload nginx
      service: name=nginx state=reloaded

    - name: reload postfix
      service: name=postfix state=reloaded

    - name: reload dovecot
      service: name=dovecot state=reloaded

    - name: update aliases db
      command: newaliases

    - name: update virtual alias maps db
      command: postmap /etc/postfix/virtual

    - name: update login maps db
      command: postmap /etc/postfix/login_maps

    - name: restart spamass-milter
      service: name=spamass-milter state=restarted

    - name: restart spamassassin daemon
      service: name=spamassassin state=restarted

    - name: restart opendkim
      service: name=opendkim state=restarted

    - name: pre-compile default sieve
      command: sievec /var/lib/dovecot/sieve/default.sieve
